# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 21:08


from django.db import migrations, models
import django.db.models.deletion

import quiz

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default=b'')),
                ('result', models.CharField(choices=[(b'OK', b'is compilable and deterministic'), (b'CE', b'has a compilation error'), (b'US', b'is unspecified'), (b'UD', b'is undefined')], default=b'OK', max_length=2)),
                ('answer', models.CharField(blank=True, default=b'', max_length=200)),
                ('explanation', models.TextField(blank=True, default=b'', help_text=b'Refer to the standard like this: \xc2\xa7x.y\xc2\xb6z. Wrap code like this: `int i`. Wrap in stars to ***emphasize***')),
                ('hint', models.TextField(blank=True, default=b'No hint')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('author_email', models.EmailField(blank=True, default=b'', max_length=254)),
                ('difficulty', models.IntegerField(choices=[(0, b'Not set'), (1, b'Beginner'), (2, b'Intermediate'), (3, b'Expert')], default=0)),
                ('preview_key', models.CharField(blank=True, default=quiz.models.generate_preview_key, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=b'', max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(through='quiz.QuestionInQuiz', to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[(b'OK', b'is compilable and deterministic'), (b'CE', b'has a compilation error'), (b'US', b'is unspecified'), (b'UD', b'is undefined')], default=b'OK', max_length=2)),
                ('answer', models.CharField(blank=True, default=b'', max_length=200)),
                ('ip', models.CharField(blank=True, default=b'', max_length=45)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.AddField(
            model_name='questioninquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
