# Generated by Django 1.9.1 on 2016-03-17 21:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20160317_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='refused',
            field=models.BooleanField(default=False),
        ),
    ]
