# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-23 10:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_refused'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
