# Generated by Django 1.9.1 on 2018-02-27 22:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='retracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, default=b'', help_text=b'Comments for admins and contributors, not displayed on the site'),
        ),
    ]
