# Generated by Django 1.11.23 on 2020-09-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20200921_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('WAI', 'Waiting'), ('ACC', 'Accepted'), ('SCH', 'Scheduled'), ('REF', 'Refused'), ('PUB', 'Published'), ('RET', 'Retracted')], default='NEW', max_length=3),
        ),
    ]
