# Generated by Django 2.2.19 on 2021-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20201219_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Use markdown, and refer to the standard like this: "§[section.subsection]¶x.y".'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, default='No hint', help_text='Use markdown, and refer to the standard like this: "§[section.subsection]¶x.y".'),
        ),
    ]
