# Generated by Django 4.1.7 on 2023-03-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20230308_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersanswer',
            name='ip',
        ),
    ]
