# Generated by Django 4.2.15 on 2024-09-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_question_result_alter_usersanswer_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tweet_text',
            new_name='socials_text',
        ),
    ]
