# Generated by Django 4.2.15 on 2024-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_rename_tweet_text_question_socials_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='socials_text',
            field=models.CharField(blank=True, help_text='What to post when question gets posted on social media', max_length=280),
        ),
    ]
