# Generated by Django 4.2.15 on 2024-11-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_question_socials_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='auto_format',
            field=models.BooleanField(default=False),
        ),
    ]
