# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[(b'NEW', b'New'), (b'ACC', b'Accepted'), (b'REF', b'Refused'), (b'PUB', b'Published'), (b'RET', b'Retracted')], default=b'NEW', max_length=3),
        ),
    ]
