# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180301_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='published',
        ),
        migrations.RemoveField(
            model_name='question',
            name='refused',
        ),
        migrations.RemoveField(
            model_name='question',
            name='retracted',
        ),
    ]
