# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=b'', help_text=b'Use markdown, and refer to the standard like this: [section.subsection]\xc2\xa7x.y\xc2\xb6z.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, default=b'No hint', help_text=b'Use markdown, and refer to the standard like this: [section.subsection]\xc2\xa7x.y\xc2\xb6z.'),
        ),
    ]
