# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20191017_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish_time',
            field=models.DateTimeField(blank=True, help_text='Time of publishing (will be published then if state is "Scheduled")', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tweet_text',
            field=models.CharField(blank=True, help_text='What to tweet when question gets posted on Twitter', max_length=280),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of creation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('WAI', 'Waiting'), ('ACC', 'Accepted'), ('SCE', 'Scheduled'), ('REF', 'Refused'), ('PUB', 'Published'), ('RET', 'Retracted')], default='NEW', max_length=3),
        ),
        migrations.AlterField(
            model_name='questioninquiz',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='questioninquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='usersanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Question'),
        ),
    ]
